### ISSUE TITLE
Cant enter a menu

### ISSUE THREAD

**Issue by ReonaWest** [Syloid/RMT#1]
I cant open Smoothness and metalness.

**Comment by acastaneiras** [comment]
Send me the .fx file and I'll try to figure out what's preventing it to open

**Comment by acastaneiras** [comment]
This issue has been fixed with the [latest version of RMT(v-1.1)](https://github.com/Syloid/RMT/releases). 

The problem was he tried to open a .fx file in which some parameters on the smoothness/metalness map were exceeding the limit. Now when something like this happens, the application prompts an error screen letting you know something in your file is wrong and even though you've got something wrong in your file it lets you edit the section.
![prev2](https://user-images.githubusercontent.com/33935297/43038203-76e4e0aa-8d15-11e8-91bb-40bb4b713fc4.png)
