### ISSUE TITLE
Can't find Guide.pdf

### ISSUE THREAD

**Issue by TheWeirdOtaku** [Syloid/RMT#2]
As mentioned in the title, I cannot seem to locate the .pdf.

On another note, how do I open up the program?

**Comment by acastaneiras** [comment]
@TheWeirdOtaku Hello, I removed it since I made a [Wiki Page](https://github.com/Syloid/RMT/wiki).

You need to move the .zip you've downloaded [from here](https://github.com/Syloid/RMT/releases) to your Extension folder from raycast and Extract it there.  

![screenshot_1](https://user-images.githubusercontent.com/33935297/44540003-ed237880-a705-11e8-8b0f-934e69e160d1.png)

Then the only thing you need to do is open the .exe 

![screenshot_2](https://user-images.githubusercontent.com/33935297/44540127-41c6f380-a706-11e8-8076-9c7415fa94f6.png)

By the way, if you want the old pdf... [RMT Guide.pdf](https://github.com/Syloid/RMT/files/2315440/RMT.Guide.pdf)

**Comment by TheWeirdOtaku** [comment]
Thank you so much!
